name: Removing old artifacts
on:
  registry_package:
    types: [published]

jobs:
  delete-old-packages:
    runs-on: ubuntu-latest
    steps:
      - name: Delete package
        uses: actions/delete-package-versions@v4
        with:
          package-name: gh-ci-test
          package-type: container
          token: ${{ secrets.GITHUB_TOKEN }}
          min-versions-to-keep: 10
          delete-only-untagged-versions: 'true'
